/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tanikawa' at '17/08/24 21:14' with Gradle 2.14.1
 *
 * @author tanikawa, @date 17/08/24 21:14
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
